id: P000632
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17419
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  author: ''
  volumes:
    0ee24a09256a492080ef96a1bdcd77fc:
      image_group_id: I4PD308
      title: ''
      volume_number: 1
      total_pages: 552
